python train.py maze -K 5 --dropout 0.1 --lr 5e-4 -tbc rnd_BC -vbc BCs -rbc BC --env umaze -data_p 0.9 -wp maze_exploration -ep 1000 --rew_eval_freq 10 --train_rew_eval_num 500 --final_rew_eval_num 500 -sb rew --horizon 50 -s 1
python train.py maze -K 5 --dropout 0.1 --lr 5e-4 -tbc rnd -vbc BCs -rbc BC --env umaze -data_p 0.9 -wp maze_exploration -ep 1000 --rew_eval_freq 10 --train_rew_eval_num 500 --final_rew_eval_num 500 -sb rew --horizon 50 -s 1
python train.py maze -K 5 --dropout 0.1 --lr 5e-4 -tbc BC -vbc BCs -rbc BC --env umaze -data_p 0.9 -wp maze_exploration -ep 1000 --rew_eval_freq 10 --train_rew_eval_num 500 --final_rew_eval_num 500 -sb rew --horizon 50 -s 1
python train.py maze -K 5 --dropout 0.1 --lr 5e-4 -tbc BC -vbc BCs -rbc BC --env umaze -data_p 0.9 -wp maze_exploration -ep 1000 --rew_eval_freq 10 --train_rew_eval_num 500 --final_rew_eval_num 500 -sb rew --horizon 50 --model_class NN --suffix no_tanh -s 1
python train.py maze -K 5 --dropout 0.1 --lr 1e-4 -tbc DT_BC -vbc DT_all -rbc DT_BC --env umaze -data_p 0.9 -wp maze_exploration -ep 1000 --rew_eval_freq 10 --train_rew_eval_num 500 --final_rew_eval_num 500 -sb rew --horizon 50 --model_class DT --suffix no_tanh -s 1
python train.py maze -K 5 --dropout 0.1 --lr 5e-4 -tbc DT_BC -vbc DT_all -rbc DT_BC --env umaze -data_p 0.9 -wp maze_exploration -ep 1000 --rew_eval_freq 10 --train_rew_eval_num 500 --final_rew_eval_num 500 -sb rew --horizon 50 --model_class DT --suffix no_tanh_highlr -s 1

#python train.py maze -K 10 --dropout 0.1 --lr 5e-4 -tbc rnd_BC -vbc BCs -rbc BC --env umaze -data_p 0.9 -wp maze_exploration -ep 1000 --rew_eval_freq 10 --train_rew_eval_num 500 --final_rew_eval_num 500 -sb rew --horizon 50 -s 1
#python train.py maze -K 10 --dropout 0.1 --lr 5e-4 -tbc rnd -vbc BCs -rbc BC --env umaze -data_p 0.9 -wp maze_exploration -ep 1000 --rew_eval_freq 10 --train_rew_eval_num 500 --final_rew_eval_num 500 -sb rew --horizon 50 -s 1
#python train.py maze -K 10 --dropout 0.1 --lr 5e-4 -tbc BC -vbc BCs -rbc BC --env umaze -data_p 0.9 -wp maze_exploration -ep 1000 --rew_eval_freq 10 --train_rew_eval_num 500 --final_rew_eval_num 500 -sb rew --horizon 50 -s 1
#python train.py maze -K 10 --dropout 0.1 --lr 5e-4 -tbc BC -vbc BCs -rbc BC --env umaze -data_p 0.9 -wp maze_exploration -ep 1000 --rew_eval_freq 10 --train_rew_eval_num 500 --final_rew_eval_num 500 -sb rew --horizon 50 --model_class NN  --suffix no_tanh -s 1
#python train.py maze -K 10 --dropout 0.1 --lr 1e-4 -tbc DT_BC -vbc DT_all -rbc DT_BC --env umaze -data_p 0.9 -wp maze_exploration -ep 1000 --rew_eval_freq 10 --train_rew_eval_num 500 --final_rew_eval_num 500 -sb rew --horizon 50 --model_class DT  --suffix no_tanh -s 1
#python train.py maze -K 10 --dropout 0.1 --lr 5e-4 -tbc DT_BC -vbc DT_all -rbc DT_BC --env umaze -data_p 0.9 -wp maze_exploration -ep 1000 --rew_eval_freq 10 --train_rew_eval_num 500 --final_rew_eval_num 500 -sb rew --horizon 50 --model_class DT --suffix no_tanh_highlr -s 1
